#!/bin/bash
#SBATCH -J test                              # Job name
#SBATCH -o job_%j.out    # Name of stdout output file(%j expands to jobId)
#SBATCH -e job_%j.err    # Name of stderr output file(%j expands to jobId)
#SBATCH -N 5                                 # Total number of nodes requested
#SBATCH -n 5                                 # Total number of cores requested
#SBATCH --get-user-env                              # Tells sbatch to retrieve the users login environment
#SBATCH -t 96:00:00                                 # Time limit (hh:mm:ss)
#SBATCH --mem-per-cpu=4000                          # Memory required per allocated CPU
#SBATCH --partition=default_partition               # Which partition/queue it should run on
#SBATCH --exclude=g2-cpu-[01-11],g2-cpu-[97-99]
mpiexec -n 5 python3 test.py
